<table cellspacing="0" cellpadding="20" border="0" width="550">
<TR><TD>


    <H2 style="color: #99FF99">The story</H2>

    <P>One day, while wandering on abandoned planet you found a beautiful crystal. You took it hoping to sell it for a good price. On the way, you were attacked by two pirates who looted your ship and took the crystal. You barely managed to stay alive.</P>
    <P>As the game starts, your escape pod reaches a nearby planet. You learn that those pirates come from planet Torres and decide to go after them. You have 2000 credits on your bank account.</P>

    <br />
    <center>
    <img src="galaxy.jpg" width="400">
    </center>
    <br />

    <P>It's time to begin your quest throughout the galaxy. You start at planet Xen, and first mission is to reach planet Torres. Both current and target planet are marked with pulsing white cross on the galaxy map. The small green circle in galaxy map represents the area you can reach with current amount of fuel. You can buy more fuel at &quot;Trade&amp;Cargo&quot; screen. You ship's tank has capacity for 40 units of fuel, and that's the most you can travel within a single &quot;hyperspace jump&quot;. If you loose all fuel and don't have any money, you're stuck on the planet until you earn enough money to buy fuel to leave it. To earn money, simply Launch off in the planet's orbit and shoot some aliens to collect alien artifacts you can sell when you return to space station.</P>

    <br>
    <center>
    <a href="shot1big.png"><img src="shot1.jpg" border="0"></a> <a href="shot2big.png"><img src="shot2.jpg" border="0"></a> <br>
    <a href="shot3big.png"><img src="shot3.jpg" border="0"></a> <a href="shot4big.png"><img align="top" src="shot4.jpg" border="0"></a> <br>
    <br>
    <a href="index.php?page=Manual">more...</a>
    </center>

</TD></TR>
</table>
