<table cellspacing="0" cellpadding="20" border="0">
<TR bgcolor="white"><TD nowrap>

    <P>Attic Manager is software used to build and maintain database of your assets:
    </P>

    <UL>
        <LI>Keep track of all the stuff you have </LI>
        <LI>Look up something <strong>when you forget</strong> where you stored it </LI>
        <LI>In case of disaster, have the list ready for the <strong>insurance</strong> company </LI>
        <LI>Keep record of <strong>things you borrowed</strong> to others</LI>
        <LI>Note repairs and maintenance costs</LI>
        <LI>Keep track of things you put in boxes <strong>when you move</strong></LI>
        <LI>Find stuff stored in your attic or basement without getting your hands dirty</LI>
        <LI>Track multiple locations of <strong>your business</strong></LI>
        <LI>UTF8 enabled - enter data in any language you use</LI>
        <LI>Modern, easy to use interface</LI>
        <LI><a href="index.php?page=Download">Try it now</a> or <a href="index.php?page=Features">Learn more...</a></LI>
    </UL>

    <br>
    <center>
    <a href="shot1big.png"><img src="shot1.jpg" border="0" alt="Main screen with list of items"></a> <a
       href="shot2big.png"><img src="shot2.jpg" border="0" alt="Item details"></a> <br>
    <a href="shot3big.png"><img src="shot3.jpg" border="0" alt="Print preview screen"></a> <a
       href="shot4big.png"><img src="shot4.jpg" border="0" alt="Thumbnail view" align="top"></a> <br>
    <br>
    <a href="index.php?page=Features">more...</a>
    </center>

</TD></TR>
</table>
