<br><br>
<table cellspacing="0" cellpadding="5" border="0" width="600" bgcolor="white">

<TR>
<TD valign="top"><a href="shot1big.png"><IMG align=right width="280" src="shot1.jpg"  border="0"></a></td>
<TD valign="top" align="left"><br>Able to track <B>unlimited number of locations</B>. This
way you can keep track of your house, flat, garage, offices of your business, etc. </td>
</TR>

<TR>
<TD valign="top"><a href="shotboxbig.png"><IMG width="280" src="shotbox.jpg" border="0" align="right"></a></TD>
<TD valign="top" align="left"><br>Unlimited levels of sublocations: rooms, attic, basement, closets, boxes, whatever you need.</TD>
</TR>

<TR>
<TD valign="top"><a href="shot2big.png"><IMG width="280" src="shot2.jpg" border="0" align="right"></a></TD>
<TD valign="top" align="left"><br>Able to store <B>unlimited number of items</B>. The only limitation is space on your hard disk.</TD>
</TR>

<TR>
<TD valign="top"><a href="shot4big.png"><IMG width="280" src="shot4.jpg" border="0" align="right"></a></TD>
<TD valign="top" align="left"><br>Able to store <B>unlimited number of photos</B> for each item.</TD>
</TR>

<TR>
<TD valign="top"><a href="shotcropbig.png"><IMG width="280" src="shotcrop.jpg" alt="Cropping the image" border="0" align="right"></a></td>
<TD valign="top" align="left"><br>Integrated photo manipulation tools to <B>crop and rotate photos</B> so you don't have to use 3rd party programs.</td>
</TR>

<TR>
<TD valign="top"><a href="shotchangesbig.png"><IMG width="280" src="shotchanges.jpg" alt="Changes and notes" border="0" align="right"></a></td>
<TD valign="top" align="left"><br>Unlimited number of changes and notes can be added: track all the maintenance costs, upgrades, borrowing things
    to others, etc.</TD>
</TR>


<TR>
<TD valign="top"><a href="shotsearchbig.png"><IMG width="280" src="shotsearch.jpg" alt="Search thumbnails" border="0" align="right"></a></td>
<TD valign="top" align="left"><br>Use <B>powerful search</B> together with thumbnail view to quickly find what you're looking for.</TD>
</TR>

<TR>
<TD valign="top"><a href="shotexportbig.png"><IMG width="280" src="shotexport.jpg" alt="Export" border="0" align="right"></a></td>
<TD valign="top" align="left"><br>Ability to export data in CSV format, so that it can be loaded into Microsoft Excel, OpenOffice or some 3rd party
    applications.</TD>
</TR>

<TR>
<TD valign="top"><a href="shot3big.png"><IMG width="280" src="shot3.jpg" border="0" align=right></a></td>
<TD valign="top" align="left"><br>Printing support with customizable reports with or without photos.</TD>
</TR>

<TR>
<TD valign="top"><a href="shotutf8big.png"><IMG width="280" src="shotutf8.jpg" border="0" align=right></a></td>
<TD valign="top" align="left"><br>Fully UTF-8 enabled. You can type item data in whatever language you use.</TD>
</TR>

<TR>
<TD valign="top"><a href="shotbackupbig.png"><IMG width="280" src="shotbackup.jpg" border="0" align=right></a></td>
<TD valign="top" align="left"><br>Stores entire database in a single file (<B>photos included!</B>) making it easy to copy it around.</TD>
</TR>


</table>

<br>
<center><a href="index.php?page=Download" style="font-family: Sans-serif;">Download...</a></center>
