<table cellspacing="0" cellpadding="20" border="0">
<TR bgcolor="white"><TD width="550" align="left">

<h2>User manual</h2>

Contents:

<ol>
<li>How to start?</li>
<li>Recording changes</li>
<li>Searching</li>
<li>Export data to Microsoft Excel or OpenOffice</li>
<li>Keeping your data safe</li>
</ol>

<br><br>
<h3>How to start?</h3>

<ul>
<li>Add your main locations: house, flat, office, etc.</li>
<li>Add sub-locations: rooms, attic, basement, garage, yard</li>
<li>Add items</li>
</ul>

<p>It is very useful to prepare photos of items. Easiest way is
to take a digital camera with you and take shots (or use scanner
to scan regular photos). To work faster through it,
you can have multiple items in a single photo - the
software has the option to cut out a piece you need using the <em>Crop</em> option:</p>

<center>
<a href="shotcropbig.png"><IMG src="shotcrop.jpg" alt="Screenshot - cropping the image" border="0"></a>
</center>
<br>
<p>If you have boxes in attic or basement, or you're
moving, it's a good idea to label the boxes (ex. box1, box2,
box3...) and keep track which item is in
which box. Later when you need something, you can
easily locate in which box
is it, so you don't have to open half of them to find
the item:
</p>

<center>
<a href="shotboxbig.png"><IMG src="shotbox.jpg" alt="Screenshot - adding a box" border="0"></a>
</center>

<br><br>
<h3>Recording changes</h3>

<ul>
<li>When you borrow stuff to someone, record it [<em>Changes and Notes</em> screen]</li>
<li>When you have expenses like maintenance or upgrade, add those as well</li>
<li>If you move item permanently from one to another location, move it in program as well [<em>Move</em> button]</li>
<li>If you don't have some items anymore, you can either add a note that you  sold it, or delete it from database. Deleting item
  only moves it to the <em>Recycle Bin</em>. When you delete it from there it is removed permanently.</li>
</ul>

<center>
<a href="shotchangesbig.png"><IMG src="shotchanges.jpg" alt="Changes and notes screen" border="0"></a>
</center>

<br><br>
<h3>Searching</h3>

<p>Looking for something in particular? Search is very powerful and searches for
entered text in all items' properties. Most
of the things are easier to recognize visually, so
it's a good idea to switch to thumbnail view when searching:</p>
<br>
<center>
<a href="shotsearchbig.png"><IMG src="shotsearch.jpg" alt="Search visually with thumbnail view" border="0"></a>
</center>


<br><br>
<h3>Export data to Excel or OpenOffice</h3>

<p>You can export all item data in CSV format. If you want to load data in Excel or OpenOffice make sure
you select CSV format. Program exports all data that is shown in the list. If you wish to export everything
select <em>My Locations</em> and turn off any search you have started, so that list contains all the items. The
same applies to printing: program
will only print items in the list, so make sure whatever you want to print or export is shown there.</p>

<center>
<a href="shotexportbig.png"><IMG src="shotexport.jpg" alt="Exporting data to Excel or OpenOffice" border="0"></a>
</center>

<br><br>
<h3>Keeping your data safe</h3>

<p>It's a good idea to do backups of your database
periodically [<em>Database-&gt;Backup</em> menu]
The program stores the entire backup in a single file,
even your photos get in
there, so you should just copy that one file to some
safe place: for example,
you can burn it to CD or send to some trusted friend
or a family member.</p>

<center>
<a href="shotbackupbig.png"><IMG src="shotbackup.jpg" alt="Backing up the database" border="0"></a>
</center>

<br><br>

</TD></TR>
</table>
