<table cellspacing="0" cellpadding="20" border="0" width="600">
<TR bgcolor="white"><TD>

<B>Price list</B>

<P>Buying the full version entitles you to free support by e-mail and
free upgrades to any future version of Attic Manager. The Attic Manager Full
Version costs 29.99 USD or equivallent amount in other currency.</P>

<UL>
    <LI>Full version for regular users - $29.99</LI>
</UL>

<br>
<br>
<B>How To Order</B>

<P>The payment is handled by <a href="http://www.shareit.com/">Share-it!</a>, one of the world's leading sellers for shareware software. You can buy full version of Attic Manager using a credit card (all major credit cards accepted), by sending a check, bank draft, cash or through a bank/wire transfer. You can also send your details by fax or phone instead of using the online services. US dollars, Euros and many other currencies are accepted. You can place your order in English, Spanish, Italian, French, German and other languages.</P>

<P>To order Attic Manager full version <a href="https://secure.shareit.com/shareit/checkout.html?PRODUCT[300151338]=1&cartcoupon=1&DELIVERY[300151338]=EML&stylefrom=300151338&backlink=http%3A%2F%2Fwww.guacosoft.com%2Fattic%2F">click here</a>.</P>

<br><br>
<B>Need help with payment system?</B>

<P>The online <a href="http://www.shareit.com/ccc/index.html?publisherid=200049645&languageid=1">customer care center</a> of our partner Share-it! answers many questions about the order process. If you cannot find the answer to your question regarding the purchase process in the customer care center, please send an email to <a href="mailto:support@shareit.com">support@shareit.com</a> or call</P>

<UL>
    <LI><font color="#006600">+1 800 903 4152</font> or <font color="#006600">+1 724 850 8186</font> in the US (languages: English)</LI>
    <LI><font color="#006600">+49 221 31088 20</font> in Europe (languages: German, English, French, Italian, Spanish, Portuguese)</LI>
</UL>

<P>Feel free to contact us should you have any questions.</P>


</TD></TR>
</table>