<table cellspacing="0" cellpadding="20" border="0">
<TR bgcolor="white"><TD width="550" align="left">

<B>E-mail</B>

<P>If you have any questions, problems or suggestions, please e-mail us
at: <font color=blue>office&#064;guacosoft.com</font>.
Make sure you write in the version of Attic Manager you're using and full version of operating
system on which you run it, for example:</P>

<UL>
    <LI>Windows XP Professional Edition - Service Pack 2</LI>
    <LI>Ubuntu Linux 6.10</LI>
</UL>


<br>
<B>Direct contact</B><br><br>
<FORM action="email" method=post>
<table cellpadding="5" cellspacing="0" border="0" bgcolor="#EEEEEE">
<TR>
    <TD>Your name:</TD>
    <TD><INPUT type=text name=ime></TD>
</TR>
<TR>
    <TD>E-mail address:</TD>
    <TD><INPUT type=text name=mejl></TD>
</TR>
<TR>
    <TD></TD>
    <TD></TD>
</TR>
<TR>
    <TD valign="top">Your question:</TD>
    <TD><TEXTAREA name=pitanje cols=40 rows=5></TEXTAREA></TD>
</TR>
<TR>
    <TD colspan="2" align="right">
    <B><font color=maroon>This option is currently not functional.<br>
    Please use the e-mail option from above.</font></B>
    <!-- input type="submit" name="submit" value="Send" -->
    </TD>
</TR>
</TABLE>
</FORM>

<P>Please make sure you leave the correct e-mail address, otherwise we won't be able to contact you back.</P>

</TD></TR>
</table>