<center>
<table border="0" cellspacing="0" cellpadding="0" width="600">
    <TR>
        <TD valign="top">
            <br>
            <H1>About us</H1>

            <P>GuacoSoft.com is a small software company based in Subotica, Serbia. It was
            started in 2006. by Milan Babuskov, renown author of many open source software in
            attempt to support myself financially and allowing me to focus on development of
            quality OSS software in the future.</P>

            <br /><br />
            <H1>Contact information</H1>
            Milan Babuskov<br />
            Stevana Filipovica 62/3<br />
            24000 Subotica<br />
            Serbia<br />
            </H>

            <P>E-mail: <font color=blue>office&#064;guacosoft.com</font></P>
        </TD>
    </TR>
</table>
</center>
