<div class="container spacer">
    <div class="levi">
            <br>
            <center>
            <H1>Njam&trade; 2</H1>
            <H2>Pac-man type of game</H2>
            </center>

            <UL>
                <LI>Sequel to award-winning Njam arcade</LI>
                <LI>Single player campaign</LI>
                <LI>Cooperative mode where two players work together to complete levels</LI>
                <LI>Duel mode where players compete with each other</LI>
                <LI>Network play for up to four players</LI>
                <LI>Great graphics, music and sound effects</LI>
                <LI>150 brand new high quality levels</LI>
                <LI>Integrated level editor enables you to extend the playing time</LI>
                <LI>Joystick/joypad support</LI>
            </UL>
            <br />
    </div>
    <div class="desni">
            <br>
            <center>
            <H1>Attic Manager&trade;</H1>
            <H2>Home inventory software</H2>
            </center>

            <UL>
                <LI>Keep track of all the stuff you have </LI>
                <LI>Look up something <strong>when you forget</strong> where you stored it </LI>
                <LI>In case of disaster, have the list ready for the <strong>insurance</strong> company </LI>
                <LI>Keep record of <strong>things you borrowed</strong> to others</LI>
                <LI>Note repairs and maintenance costs</LI>
                <LI>Keep track of things you put in boxes <strong>when you move</strong></LI>
                <LI>Find stuff stored in your attic or basement without getting your hands dirty</LI>
                <LI>Track multiple locations of <strong>your business</strong></LI>
                <LI>UTF8 enabled - enter data in any language you use</LI>
                <LI>Modern, easy to use interface</LI>
            </UL>
            <br />
    </div>
</div>

<div class="container spacer">
    <div class="levi">
        <center>
        <a href="njam/"><img src="njam350.jpg" alt="Screenshot" border="0"></a>
        <br />
        <a href="njam/">More...</a>
        </center>
    </div>
    <div class="desni">
        <center>
        <a href="attic/"><img src="attic350.jpg" alt="Screenshot" border="0"></a>
        <br />
        <a href="attic/">More...</a>
        </center>
    </div>
</div>

<br><br>

<!-- SiteSearch Google -->
<form method="get" action="http://www.google.com/custom" target="_top">
<table border="0" bgcolor="#ffffff">
<tr><td nowrap="nowrap" valign="top" align="left" height="32">
<a href="http://www.google.com/">
<img src="http://www.google.com/logos/Logo_25wht.gif" border="0" alt="Google" align="middle"></img></a>
</td>
<td nowrap="nowrap">
<input type="hidden" name="domains" value="www.guacosoft.com"></input>
<label for="sbi" style="display: none">Enter your search terms</label>
<input type="text" name="q" size="31" maxlength="255" value="" id="sbi"></input>
<label for="sbb" style="display: none">Submit search form</label>
<input type="submit" name="sa" value="Search" id="sbb"></input>
</td></tr>
<tr>
<td>&nbsp;</td>
<td nowrap="nowrap">
<table>
<tr>
<td>
<input type="radio" name="sitesearch" value="" checked id="ss0"></input>
<label for="ss0" title="Search the Web"><font size="-1" color="#000000">Web</font></label></td>
<td>
<input type="radio" name="sitesearch" value="www.guacosoft.com" id="ss1"></input>
<label for="ss1" title="Search www.guacosoft.com"><font size="-1" color="#000000">www.guacosoft.com</font></label></td>
</tr>
</table>
<input type="hidden" name="client" value="pub-2072430600789119"></input>
<input type="hidden" name="forid" value="1"></input>
<input type="hidden" name="channel" value="2966737701"></input>
<input type="hidden" name="ie" value="ISO-8859-1"></input>
<input type="hidden" name="oe" value="ISO-8859-1"></input>
<input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#CCDDFF;VLC:663399;AH:center;BGC:FFFFFF;LBGC:FFFFFF;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;LH:30;LW:214;L:http://www.guacosoft.com/guacosoft.gif;S:http://www.guacosoft.com;FORID:1"></input>
<input type="hidden" name="hl" value="en"></input>
</td></tr></table>
</form>
<!-- SiteSearch Google -->
