<table border="0" cellspacing="0" cellpadding="0" width="765">
	<TR>
		<TD valign="top" width="50%">
			<br>
			<center>
			<H1>Scum of the Universe&trade;</H1>
			<H2>Space trading game</H2>
			</center>

			<P>Scum of the Universe is a space trading game that combines two genres: arcade and strategy. On one side, it's a classic vertical-scrolling <B>space shooter</B> game. On the other side, it is an adventure and strategy. You should choose whether you'll be an independent space trader, firearms smuggler, fierce freedom-fighter or something in between.</P> 

			<P>Following the main storyline, you go through the galaxy from one planet to another. Space travel requires fuel, so you need to keep earning money to buy it. You can also buy various upgrades for your spaceship and weapons that affect the arcade part of the game. The storyline itself is not linear. There are also some points where you'll need to make decisions that will determine your destiny.</P>
			<br />
		</TD>
		<TD valign="top">
			<br>
			<center>
			<H1>Attic Manager&trade;</H1>
			<H2>Home inventory software</H2>
			</center>

			<UL>
				<LI>Keep track of all the stuff you have </LI>
				<LI>Look up something <strong>when you forget</strong> where you stored it </LI>
				<LI>In case of disaster, have the list ready for the <strong>insurance</strong> company </LI>
				<LI>Keep record of <strong>things you borrowed</strong> to others</LI>
				<LI>Note repairs and maintenance costs</LI>
				<LI>Keep track of things you put in boxes <strong>when you move</strong></LI>
				<LI>Find stuff stored in your attic or basement without getting your hands dirty</LI>
				<LI>Track multiple locations of <strong>your business</strong></LI>
				<LI>UTF8 enabled - enter data in any language you use</LI>
				<LI>Modern, easy to use interface</LI>
				<LI><a href="attic/index.php">Learn more...</a></LI>
			</UL>
			<br />
		</TD>
	</TR>
	<TR>
		<TD align="center">
			<a href="scum/"><img src="scum350.jpg" alt="Screenshot" border="0"></a>
			<br />
			<a href="scum/">More...</a>
		</TD>
		<TD align="center">
			<a href="attic/"><img src="attic350.jpg" alt="Screenshot" border="0"></a>
			<br />
			<a href="attic/">More...</a>
		</TD>
	</TR>
</table>
