<style>
td { font-family: Arial; font-size: 12px; }
</style>
<table width=740 bgcolor=white border=0 cellspacing=20>
    <tr>
        <td>
            <a href="njam/"><img src="njam350.jpg" alt="Screenshot" border="0"></a>
        </td>
        <td>
            <H1>Njam&trade; 2</H1>
            <H2>Pac-man type of game</H2>

            <UL>
                <LI>Sequel to award-winning Njam classic</LI>
                <LI>Single player campaign</LI>
                <LI>Cooperative mode where two players work together to complete levels</LI>
                <LI>Duel mode where players compete with each other</LI>
                <LI>Network play for up to four players</LI>
                <LI>Great graphics, music and sound effects</LI>
                <LI>150 brand new high quality levels</LI>
                <LI>Integrated level editor enables you to extend the playing time</LI>
                <LI>Joystick/joypad support</LI>
            </UL>
        </td>
    </tr>

    <tr>
        <td>
            <a href="attic/"><img src="attic350.jpg" alt="Screenshot" border="0"></a>
        </td>
        <td>
            <H1>Attic Manager&trade;</H1>
            <H2>Home inventory software</H2>

            <UL>
                <LI>Keep track of all the stuff you have </LI>
                <LI>Look up something <strong>when you forget</strong> where you stored it </LI>
                <LI>In case of disaster, have the list ready for the <strong>insurance</strong> company </LI>
                <LI>Keep record of <strong>things you borrowed</strong> to others</LI>
                <LI>Note repairs and maintenance costs</LI>
                <LI>Keep track of things you put in boxes <strong>when you move</strong></LI>
                <LI>Find stuff stored in your attic or basement without getting your hands dirty</LI>
                <LI>Track multiple locations of <strong>your business</strong></LI>
                <LI>UTF8 enabled - enter data in any language you use</LI>
                <LI>Modern, easy to use interface</LI>
            </UL>
        </td>
    </tr>

    <tr>
        <td>
            <a href="scum/"><img src="scum350.jpg" alt="Screenshot" border="0"></a>
        </td>
        <td>
            <H1>Scum of the Universe&trade;</H1>
            <H2>Space trading game</H2>
            </center>

            <P>Scum of the Universe is a space trading game that combines two genres: arcade and strategy. On one side, it's a classic vertical-scrolling <B>space shooter</B> game. On the other side, it is an adventure and strategy. You should choose whether you'll be an independent space trader, firearms smuggler, fierce freedom-fighter or something in between.</P>

            <P>Following the main storyline, you go through the galaxy from one planet to another. Space travel requires fuel, so you need to keep earning money to buy it. You can also buy various upgrades for your spaceship and weapons that affect the arcade part of the game. The storyline itself is not linear. There are also some points where you'll need to make decisions that will determine your destiny.</P>
            <br />
        </td>
    </tr>

    <tr>
        <td>
            <a href="slagalica/mojbroj.php"><img src="slagalica/mojbroj.jpg" alt="Screenshot" border="0"></a>
        </td>
        <td>
            <H1>Moj broj</H1>
            <H2>A puzzle game from TV show Slagalica</H2>
            </center>

            <P>Moj broj (my number) is one of the most popular games in top-rated TV quiz show <B>Slagalica</B>.
              The goal of the game is to to combine 6 numbers and basic mathematical operations (add,
              subtract, multiply, divide) to get the target number. Four of those numbers are single
              digit, one is either of 10, 15 or 20 and sixth is either of 25, 50, 75 and 100. The
              number of operations is not limited, but each number can be used only once.</P>
            <P>This is a free online game, you only need your web browser to play it.</P>
            <br />
        </td>
    </tr>

</table>
