<center>
<table border="0" cellspacing="0" cellpadding="0" width="600">
    <TR>
        <TD valign="top">
            <br>
            <H1>Shop</H1>

            <P>All online transactions are handled by <a href="http://www.shareit.com">ShareIt!</a>,
            one of the world's leading seller of shareware software. You can buy our products
            using a credit card (all major credit cards accepted), by sending a check, bank
            draft, cash or through a bank/wire transfer and also PayPal. You can also send your
            details by fax or phone instead of using the online services. US dollars, Euros and
            many other currencies are accepted. You can place your order in English, Spanish,
            Italian, French, German and other languages. Please visit our online shop:
            <br /><br />
            <a href="https://secure.shareit.com/shareit/checkout.html?PRODUCT[300151338]=1&cartcoupon=1&DELIVERY[300151338]=EML&stylefrom=300151338">Order page for Attic Manager</a></P>
            <a href="https://secure.shareit.com/shareit/checkout.html?PRODUCT[300137230]=1&languageid=1&stylefrom=300151338">Order page for Scum of the Universe</a>
        </TD>
    </TR>
</table>
</center>
